[package]
name = "Hydrogen"
version = "0.0.2-alpha"
edition = "2024"
description = "A simple strategy game."
repository = "https://github.com/Focasius/Hydrogen"
license = "	AGPL-3.0"

[dependencies]
rand = "0.9.2"
